const data = {
  Afghanistan: "Kabul",
  Argentina: "Buenos Aires",
  Bolivia: "La Paz",
  Brazil: "Brasília",
  Canada: "Ottawa",
  Chile: "Santiago",
  China: "Beijing",
  Cuba: "Havana",
  Egypt: "Cairo",
  England: "London",
  France: "Paris",
  Germany: "Berlin",
  India: "New Delhi",
  Ireland: "Dublin",
  Israel: "Jerusalem",
  Italy: "Roma",
  Japan: "Tokyo",
  Peru: "Lima",
  Portugal: "Lisboa",
  "Russian Federation": "Moscow",
  "South Korea": "Seoul",
  Spain: "Madrid",
  Ukraine: "Kyiv",
  "United Arab Emirates": "Abu Dhabi",
  "United States": "Washington",
};

export { data };
